version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: conda run -n interview_better uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    depends_on:
      - redis

  frontend:
    image: node:20
    container_name: angular-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run start"
    ports:
      - "4200:4200"
    depends_on:
      - backend

  redis:
    image: redis:alpine
    container_name: redis-server
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"