name: interview_better
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - fastapi
  - uvicorn
  - redis
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - jinja2
  - httpx
  - requests
  - ipykernel
  - jupyter
  - pip:
      - absl-py
      - annotated-types
      - anyio==4.6.2
      - charset-normalizer
      - click
      - dotenv
      - filelock
      - flatbuffers
      - fsspec
      - fuzzywuzzy
      - gast
      - google-pasta
      - grpcio
      - h5py
      - huggingface-hub
      - idna
      - jiter
      - keras
      - levenshtein
      - libclang
      - llvmlite
      - markdown
      - markdown-it-py
      - mdurl
      - ml-dtypes
      - more-itertools
      - mpmath
      - namex
      - networkx
      - numba
      - openai
      - openai-whisper
      - opt-einsum
      - optree
      - protobuf
      - pydantic
      - pydantic-core
      - pygments
      - python-dotenv
      - python-levenshtein
      - rapidfuzz
      - redis
      - regex
      - rich
      - safetensors
      - six
      - starlette
      - sympy
      - tensorboard
      - tensorboard-data-server
      - tensorflow
      - tensorflow-io-gcs-filesystem
      - termcolor
      - tf-keras
      - tiktoken
      - tokenizers
      - torch
      - torchaudio
      - torchvision
      - tqdm
      - transformers
      - uvicorn
      - werkzeug
      - wrapt